.gitignore, envpool/atari/BUILD, envpool/atari/__init__.py, envpool/atari/api_test.py, envpool/atari/atari_pretrain_test.py
otherwise when someone changes the code in another folder, it will also trigger the atari tests
=> minimize atari test dependency

envpool/atari/api_test.py, envpool/make_test.py, envpool/python/env_spec.py, envpool/registration.py, examples/list_all_envs.py
If `reward_threshold` is defined in EnvFns/Config, `env.spec.reward_threshold` will be that value; otherwise, it would be `None`.
=> add reward_threshold

envpool/BUILD, envpool/atari/BUILD, envpool/atari/registration.py
https://github.com/sail-sg/envpool/pull/25#discussion_r753741887
=> split registration to per-env

README.md, docs/index.rst, docs/pages/build.rst, docs/pages/contributing.rst, docs/pages/env.rst, docs/pages/interface.rst, docs/spelling_wordlist.txt, envpool/__init__.py, envpool/atari/registration.py, setup.cfg
=> how to integrate new env into envpool (second part)

README.md, docs/api/classic.rst, docs/index.rst, docs/spelling_wordlist.txt, envpool/classic_control/BUILD, envpool/classic_control/__init__.py, envpool/classic_control/acrobot.h, envpool/classic_control/cartpole.h, envpool/classic_control/catch.h, envpool/classic_control/classic_control.cc, envpool/classic_control/classic_control_test.py, envpool/classic_control/mountain_car.h, envpool/classic_control/mountain_car_continuous.h, envpool/classic_control/mountain_car_discrete.h, envpool/classic_control/pendulum.h, envpool/classic_control/registration.py, envpool/core/py_envpool.h, envpool/make_test.py, envpool/python/data.py, examples/tianshou_examples/pendulum_ppo.py
=> port classic_control envs

docs/api/atari.rst, docs/pages/interface.rst, envpool/atari/atari_env.h, envpool/atari/atari_env_test.cc, envpool/utils/image_process.h, examples/benchmark.py
#21
Most of the time, there's no difference between (gray_scale -> maxpool) and (maxpool -> gray_scale) wrappers' result. But the former is quicker than the latter.
=> match atari speed to v0.4.0

.github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test.yml, Makefile, docker/release.dockerfile, docs/pages/build.rst, envpool/atari/api_test.py, envpool/workspace0.bzl
do not use docker to create release, instead, use github action for better caching and workload splitting
=> upload wheel when tag

docs/api/atari.rst, envpool/atari/BUILD, envpool/atari/atari_env.h, envpool/atari/atari_envpool_test.py
=> add atari gray_scale option

README.md, examples/sb3_examples/ppo.py
=> Add Stable-Baselines3 (SB3) example

docs/api/toy_text.rst, envpool/make_test.py, envpool/toy_text/BUILD, envpool/toy_text/__init__.py, envpool/toy_text/cliffwalking.h, envpool/toy_text/registration.py, envpool/toy_text/toy_text.cc, envpool/toy_text/toy_text_test.py
=> add cliffwalking

README.md, envpool/__init__.py, setup.cfg
=> update citation and bump to v0.4.4

docs/api/mujoco.rst, envpool/__init__.py, envpool/make_test.py, envpool/mujoco/BUILD, envpool/mujoco/__init__.py, envpool/mujoco/half_cheetah.h, envpool/mujoco/mujoco_envpool.cc, envpool/mujoco/mujoco_test.py, envpool/mujoco/registration.py, setup.cfg
=> Add HalfCheetah-v4

docs/api/mujoco.rst, docs/spelling_wordlist.txt, envpool/make_test.py, envpool/mujoco/BUILD, envpool/mujoco/__init__.py, envpool/mujoco/ant.h, envpool/mujoco/half_cheetah.h, envpool/mujoco/hopper.h, envpool/mujoco/humanoid.h, envpool/mujoco/mujoco_envpool.cc, envpool/mujoco/mujoco_test.py, envpool/mujoco/registration.py
=> Humanoid-v4

docs/api/mujoco.rst, envpool/make_test.py, envpool/mujoco/BUILD, envpool/mujoco/__init__.py, envpool/mujoco/humanoid_standup.h, envpool/mujoco/mujoco_envpool.cc, envpool/mujoco/mujoco_test.py, envpool/mujoco/registration.py
=> HumanoidStandup-v4

docs/api/mujoco.rst, envpool/make_test.py, envpool/mujoco/BUILD, envpool/mujoco/__init__.py, envpool/mujoco/ant.h, envpool/mujoco/half_cheetah.h, envpool/mujoco/hopper.h, envpool/mujoco/humanoid.h, envpool/mujoco/inverted_pendulum.h, envpool/mujoco/mujoco_envpool.cc, envpool/mujoco/mujoco_test.py, envpool/mujoco/registration.py
=> InvertedPendulum-v4

docs/api/mujoco.rst, envpool/make_test.py, envpool/mujoco/BUILD, envpool/mujoco/__init__.py, envpool/mujoco/mujoco_envpool.cc, envpool/mujoco/mujoco_test.py, envpool/mujoco/registration.py, envpool/mujoco/swimmer.h
=> Swimmer-v4

README.md, docs/api/mujoco.rst, docs/spelling_wordlist.txt, envpool/make_test.py, envpool/mujoco/BUILD, envpool/mujoco/__init__.py, envpool/mujoco/mujoco_envpool.cc, envpool/mujoco/mujoco_test.py, envpool/mujoco/reacher.h, envpool/mujoco/registration.py
=> Reacher-v4

docs/api/mujoco.rst, envpool/make_test.py, envpool/mujoco/BUILD, envpool/mujoco/__init__.py, envpool/mujoco/inverted_double_pendulum.h, envpool/mujoco/mujoco_envpool.cc, envpool/mujoco/mujoco_test.py, envpool/mujoco/registration.py
=> InvertedDoublePendulum-v4

.bazelrc, .clang-tidy, .github/workflows/test.yml, BUILD, Makefile, docs/pages/contributing.rst, docs/pages/env.rst, envpool/atari/BUILD, envpool/atari/atari_env_test.cc, envpool/atari/atari_envpool.cc, envpool/atari/atari_envpool_test.py, envpool/atari/atari_pretrain_test.py, envpool/classic_control/classic_control.cc, envpool/core/action_buffer_queue_test.cc, envpool/core/async_envpool.h, envpool/core/dict_test.cc, envpool/core/state_buffer.h, envpool/core/state_buffer_queue.h, envpool/core/state_buffer_queue_test.cc, envpool/core/state_buffer_test.cc, envpool/dummy/dummy_envpool.cc, envpool/dummy/dummy_envpool_test.cc, envpool/mujoco/mujoco_envpool.cc, envpool/toy_text/toy_text.cc, envpool/vizdoom/vizdoom_envpool.cc, envpool/vizdoom/vizdoom_pretrain_test.py, envpool/workspace0.bzl
Use `make bazel-clang-tidy` to perform check.
`make bazel-debug` will build everything in debug mode.
=> Add clang-tidy

docs/api/mujoco.rst, envpool/make_test.py, envpool/mujoco/BUILD, envpool/mujoco/__init__.py, envpool/mujoco/mujoco_envpool.cc, envpool/mujoco/mujoco_test.py, envpool/mujoco/registration.py, envpool/mujoco/walker2d.h
=> Walker2d-v4

docker/dev.dockerfile, envpool/workspace0.bzl
- Update for parent docker image
- Update for bazel dependencies
=> Fix minor errors for local development of envpool

.bazelrc, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/release.yml, .github/workflows/test.yml, Makefile, docs/pages/build.rst, docs/pages/contributing.rst, envpool/__init__.py, setup.cfg
1. polish compile option in `.bazelrc` to hit bazel cache most of the time
2. add pull request template
=> bump version to v0.5.2

README.md, docs/pages/interface.rst, envpool/__init__.py, envpool/atari/atari_env.h, envpool/core/env_spec.h, envpool/dummy/dummy_py_envpool_test.py, envpool/mujoco/mujoco_test.py, envpool/python/dm_envpool.py, envpool/python/envpool.py, envpool/python/gym_envpool.py, envpool/python/protocol.py, setup.cfg
=> Add gym_reset_return_info option to adapt with newest gym API

envpool/__init__.py, envpool/core/async_envpool.h, setup.cfg
=> Fix thread_affinity_offset==-1

docs/api/dm_control.rst, envpool/make_test.py, envpool/mujoco/BUILD, envpool/mujoco/__init__.py, envpool/mujoco/dmc/cheetah.h, envpool/mujoco/dmc/mujoco_dmc_align_test.py, envpool/mujoco/dmc/mujoco_dmc_deterministic_test.py, envpool/mujoco/dmc/mujoco_env.h, envpool/mujoco/dmc/mujoco_envpool.cc, envpool/mujoco/registration.py
=> dmc cheetah

docs/api/dm_control.rst, envpool/make_test.py, envpool/mujoco/BUILD, envpool/mujoco/__init__.py, envpool/mujoco/dmc/mujoco_dmc_align_test.py, envpool/mujoco/dmc/mujoco_dmc_deterministic_test.py, envpool/mujoco/dmc/mujoco_envpool.cc, envpool/mujoco/dmc/walker.h, envpool/mujoco/registration.py
=> dmc walker

docs/api/dm_control.rst, envpool/make_test.py, envpool/mujoco/BUILD, envpool/mujoco/__init__.py, envpool/mujoco/dmc/cheetah.h, envpool/mujoco/dmc/hopper.h, envpool/mujoco/dmc/mujoco_dmc_align_test.py, envpool/mujoco/dmc/mujoco_dmc_deterministic_test.py, envpool/mujoco/dmc/mujoco_envpool.cc, envpool/mujoco/dmc/reacher.h, envpool/mujoco/dmc/walker.h, envpool/mujoco/registration.py
=> dmc reacher

docs/api/dm_control.rst, envpool/make_test.py, envpool/mujoco/BUILD, envpool/mujoco/__init__.py, envpool/mujoco/dmc/ball_in_cup.h, envpool/mujoco/dmc/finger.h, envpool/mujoco/dmc/mujoco_dmc_align_test.py, envpool/mujoco/dmc/mujoco_dmc_deterministic_test.py, envpool/mujoco/dmc/mujoco_envpool.cc, envpool/mujoco/registration.py
=> dmc ball_in_cup

docs/api/dm_control.rst, envpool/make_test.py, envpool/mujoco/BUILD, envpool/mujoco/__init__.py, envpool/mujoco/dmc/mujoco_dmc_align_test.py, envpool/mujoco/dmc/mujoco_dmc_deterministic_test.py, envpool/mujoco/dmc/mujoco_envpool.cc, envpool/mujoco/dmc/pendulum.h, envpool/mujoco/dmc/point_mass.h, envpool/mujoco/registration.py
=> dmc point mass

docs/api/dm_control.rst, envpool/make_test.py, envpool/mujoco/BUILD, envpool/mujoco/__init__.py, envpool/mujoco/dmc/acrobot.h, envpool/mujoco/dmc/ball_in_cup.h, envpool/mujoco/dmc/cheetah.h, envpool/mujoco/dmc/finger.h, envpool/mujoco/dmc/hopper.h, envpool/mujoco/dmc/mujoco_dmc_align_test.py, envpool/mujoco/dmc/mujoco_dmc_deterministic_test.py, envpool/mujoco/dmc/mujoco_envpool.cc, envpool/mujoco/dmc/pendulum.h, envpool/mujoco/dmc/point_mass.h, envpool/mujoco/dmc/reacher.h, envpool/mujoco/dmc/walker.h, envpool/mujoco/registration.py
=> dmc acrobot

.github/workflows/release.yml, README.md, benchmark/README.md, docs/content/benchmark.rst, docs/content/new_env.rst, examples/sb3_examples/ppo.py, examples/tianshou_examples/pendulum_ppo.py
Also replace all `Pendulum-v0` with `Pendulum-v1` in all examples.
=> Switch from master to main branch

envpool/__init__.py, envpool/mujoco/dmc/acrobot.h, envpool/mujoco/dmc/ball_in_cup.h, envpool/mujoco/dmc/cheetah.h, envpool/mujoco/dmc/finger.h, envpool/mujoco/dmc/fish.h, envpool/mujoco/dmc/manipulator.h, envpool/mujoco/dmc/mujoco_env.cc, envpool/mujoco/dmc/mujoco_env.h, envpool/mujoco/dmc/pendulum.h, envpool/mujoco/dmc/point_mass.h, envpool/mujoco/dmc/reacher.h, envpool/mujoco/dmc/utils.h, setup.cfg
```c++
using RandInt = std::uniform_int_distribution<>;
using RandUniform = std::uniform_real_distribution<>;
using RandNormal = std::normal_distribution<>;
```
cc @Benjamin-eecs
=> Replace dist_x_ with RandX in mujoco dmc env

docs/env/dm_control.rst, envpool/make_test.py, envpool/mujoco/BUILD, envpool/mujoco/dmc/__init__.py, envpool/mujoco/dmc/mujoco_dmc_align_test.py, envpool/mujoco/dmc/mujoco_dmc_deterministic_test.py, envpool/mujoco/dmc/mujoco_envpool.cc, envpool/mujoco/dmc/reacher.h, envpool/mujoco/dmc/registration.py, envpool/mujoco/dmc/swimmer.h, envpool/mujoco/dmc/utils.cc, envpool/mujoco/dmc/utils.h
=> dmc swimmer

.github/workflows/release.yml, benchmark/test_dmc.py, docs/env/dm_control.rst, docs/env/mujoco_gym.rst, envpool/__init__.py, envpool/core/spec.h, envpool/mujoco/BUILD, envpool/mujoco/gym/ant.h, envpool/mujoco/gym/humanoid.h, envpool/mujoco/gym/registration.py, envpool/workspace0.bzl, setup.cfg, third_party/mujoco/mujoco.BUILD, third_party/pip_requirements/requirements.txt
Also align with newest gym because of https://github.com/openai/gym/pull/2762
=> Upgrade mujoco to 2.2.0

docs/content/new_env.rst, docs/env/atari.rst, envpool/atari/BUILD, envpool/atari/atari_env.h, envpool/atari/registration.py, envpool/make_test.py, setup.cfg, third_party/atari_roms/atari_roms.BUILD, third_party/pip_requirements/requirements.txt
=> Remove Atari wrong bin

.github/workflows/release.yml, docs/env/dm_control.rst, envpool/__init__.py, envpool/core/py_envpool.h, envpool/dummy/dummy_envpool.h, envpool/dummy/dummy_envpool_test.cc, envpool/dummy/dummy_py_envpool_test.py, envpool/mujoco/BUILD, envpool/mujoco/gym/mujoco_gym_envpool_test.cc, setup.cfg
=> Fix action ref counting error

envpool/__init__.py, envpool/python/gym_envpool.py, setup.cfg
=> fix import error with gym==0.25.0

envpool/core/async_envpool.h
=> Change default value of num_threads

.github/workflows/release.yml, docs/env/dm_control.rst, docs/env/mujoco_gym.rst, envpool/mujoco/BUILD, envpool/workspace0.bzl, third_party/mujoco/mujoco.BUILD, third_party/pip_requirements/requirements.txt
=> Upgrade mujoco to 2.2.1

.github/workflows/release.yml, README.md, docker/dev-cn.dockerfile, docker/dev.dockerfile, docker/release.dockerfile, docs/content/build.rst, envpool/__init__.py, setup.cfg
=> Add Python 3.10 Wheel

demo/envpool_demo_ant.ipynb, demo/envpool_demo_breakout.ipynb, demo/envpool_demo_halfcheetah.ipynb, demo/envpool_demo_pong.ipynb
=> fix(demo): update broken colab link

envpool/atari/api_test.py, envpool/python/dm_envpool.py, envpool/python/gym_envpool.py
=> fix gym action space seed behavior error

envpool/__init__.py, envpool/make_test.py, envpool/registration.py, setup.cfg
=> better arugment checking in python side init

.bazelrc, envpool/mujoco/gym/humanoid.h, envpool/mujoco/gym/registration.py
=> Add back contact force in humanoid-v3

docs/env/atari.rst, envpool/__init__.py, envpool/atari/atari_env.h, envpool/atari/atari_envpool_test.py, setup.cfg
=> Support atari full action space

docs/content/xla_interface.rst
Minor fix on the documentation.
What types of changes does your code introduce? Put an `x` in all the boxes that apply:
=> Docs fix on gymnasium

Makefile, docker/dev-cn.dockerfile, docker/dev.dockerfile, docker/release.dockerfile, docs/env/procgen.rst, envpool/__init__.py, envpool/procgen/procgen_env.h, envpool/procgen/procgen_env_test.cc, envpool/procgen/procgen_test.py, setup.cfg
=> Add `channel_first` option in procgen 

README.md
environment currently returns 5 values, which can't be unpacked into "done"
What types of changes does your code introduce? Put an `x` in all the boxes that apply:
=> Use new gym API in examples

docs/env/dm_control.rst
=> typo fix in `CarpoletSwingup`

envpool/python/gym_envpool.py
This fixes a bug introduced by #247
=> fix old gym version return type error

README.md
Describe your changes in detail.
Why is this change required? What problem does it solve?
If it fixes an open issue, please link to the issue here.
You can use the syntax `close #233` if this solves the issue #233
What types of changes does your code introduce? Put an `x` in all the boxes that apply:
Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!
=> Use the latest neurips citation
